# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.20.5-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.20.5-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/iktp/Geant4-Work/NewStart/NumberofMuonStopped

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/iktp/Geant4-Work/NewStart/NumberofMuonStopped

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.20.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/cmake-3.20.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.20.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/cmake-3.20.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.20.5-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/cmake-3.20.5-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.20.5-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.20.5-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iktp/Geant4-Work/NewStart/NumberofMuonStopped/CMakeFiles /home/iktp/Geant4-Work/NewStart/NumberofMuonStopped//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iktp/Geant4-Work/NewStart/NumberofMuonStopped/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exampleMuStopped

# Build rule for target.
exampleMuStopped: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exampleMuStopped
.PHONY : exampleMuStopped

# fast build rule for target.
exampleMuStopped/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/build
.PHONY : exampleMuStopped/fast

#=============================================================================
# Target rules for targets named MuStopped

# Build rule for target.
MuStopped: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MuStopped
.PHONY : MuStopped

# fast build rule for target.
MuStopped/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MuStopped.dir/build.make CMakeFiles/MuStopped.dir/build
.PHONY : MuStopped/fast

exampleMuStopped.o: exampleMuStopped.cc.o
.PHONY : exampleMuStopped.o

# target to build an object file
exampleMuStopped.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/exampleMuStopped.cc.o
.PHONY : exampleMuStopped.cc.o

exampleMuStopped.i: exampleMuStopped.cc.i
.PHONY : exampleMuStopped.i

# target to preprocess a source file
exampleMuStopped.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/exampleMuStopped.cc.i
.PHONY : exampleMuStopped.cc.i

exampleMuStopped.s: exampleMuStopped.cc.s
.PHONY : exampleMuStopped.s

# target to generate assembly for a file
exampleMuStopped.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/exampleMuStopped.cc.s
.PHONY : exampleMuStopped.cc.s

src/MuStoppedActionInitialization.o: src/MuStoppedActionInitialization.cc.o
.PHONY : src/MuStoppedActionInitialization.o

# target to build an object file
src/MuStoppedActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedActionInitialization.cc.o
.PHONY : src/MuStoppedActionInitialization.cc.o

src/MuStoppedActionInitialization.i: src/MuStoppedActionInitialization.cc.i
.PHONY : src/MuStoppedActionInitialization.i

# target to preprocess a source file
src/MuStoppedActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedActionInitialization.cc.i
.PHONY : src/MuStoppedActionInitialization.cc.i

src/MuStoppedActionInitialization.s: src/MuStoppedActionInitialization.cc.s
.PHONY : src/MuStoppedActionInitialization.s

# target to generate assembly for a file
src/MuStoppedActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedActionInitialization.cc.s
.PHONY : src/MuStoppedActionInitialization.cc.s

src/MuStoppedDetectorConstruction.o: src/MuStoppedDetectorConstruction.cc.o
.PHONY : src/MuStoppedDetectorConstruction.o

# target to build an object file
src/MuStoppedDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedDetectorConstruction.cc.o
.PHONY : src/MuStoppedDetectorConstruction.cc.o

src/MuStoppedDetectorConstruction.i: src/MuStoppedDetectorConstruction.cc.i
.PHONY : src/MuStoppedDetectorConstruction.i

# target to preprocess a source file
src/MuStoppedDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedDetectorConstruction.cc.i
.PHONY : src/MuStoppedDetectorConstruction.cc.i

src/MuStoppedDetectorConstruction.s: src/MuStoppedDetectorConstruction.cc.s
.PHONY : src/MuStoppedDetectorConstruction.s

# target to generate assembly for a file
src/MuStoppedDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedDetectorConstruction.cc.s
.PHONY : src/MuStoppedDetectorConstruction.cc.s

src/MuStoppedEventAction.o: src/MuStoppedEventAction.cc.o
.PHONY : src/MuStoppedEventAction.o

# target to build an object file
src/MuStoppedEventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedEventAction.cc.o
.PHONY : src/MuStoppedEventAction.cc.o

src/MuStoppedEventAction.i: src/MuStoppedEventAction.cc.i
.PHONY : src/MuStoppedEventAction.i

# target to preprocess a source file
src/MuStoppedEventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedEventAction.cc.i
.PHONY : src/MuStoppedEventAction.cc.i

src/MuStoppedEventAction.s: src/MuStoppedEventAction.cc.s
.PHONY : src/MuStoppedEventAction.s

# target to generate assembly for a file
src/MuStoppedEventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedEventAction.cc.s
.PHONY : src/MuStoppedEventAction.cc.s

src/MuStoppedPrimaryGeneratorAction.o: src/MuStoppedPrimaryGeneratorAction.cc.o
.PHONY : src/MuStoppedPrimaryGeneratorAction.o

# target to build an object file
src/MuStoppedPrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedPrimaryGeneratorAction.cc.o
.PHONY : src/MuStoppedPrimaryGeneratorAction.cc.o

src/MuStoppedPrimaryGeneratorAction.i: src/MuStoppedPrimaryGeneratorAction.cc.i
.PHONY : src/MuStoppedPrimaryGeneratorAction.i

# target to preprocess a source file
src/MuStoppedPrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedPrimaryGeneratorAction.cc.i
.PHONY : src/MuStoppedPrimaryGeneratorAction.cc.i

src/MuStoppedPrimaryGeneratorAction.s: src/MuStoppedPrimaryGeneratorAction.cc.s
.PHONY : src/MuStoppedPrimaryGeneratorAction.s

# target to generate assembly for a file
src/MuStoppedPrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedPrimaryGeneratorAction.cc.s
.PHONY : src/MuStoppedPrimaryGeneratorAction.cc.s

src/MuStoppedRunAction.o: src/MuStoppedRunAction.cc.o
.PHONY : src/MuStoppedRunAction.o

# target to build an object file
src/MuStoppedRunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedRunAction.cc.o
.PHONY : src/MuStoppedRunAction.cc.o

src/MuStoppedRunAction.i: src/MuStoppedRunAction.cc.i
.PHONY : src/MuStoppedRunAction.i

# target to preprocess a source file
src/MuStoppedRunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedRunAction.cc.i
.PHONY : src/MuStoppedRunAction.cc.i

src/MuStoppedRunAction.s: src/MuStoppedRunAction.cc.s
.PHONY : src/MuStoppedRunAction.s

# target to generate assembly for a file
src/MuStoppedRunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedRunAction.cc.s
.PHONY : src/MuStoppedRunAction.cc.s

src/MuStoppedSteppingAction.o: src/MuStoppedSteppingAction.cc.o
.PHONY : src/MuStoppedSteppingAction.o

# target to build an object file
src/MuStoppedSteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedSteppingAction.cc.o
.PHONY : src/MuStoppedSteppingAction.cc.o

src/MuStoppedSteppingAction.i: src/MuStoppedSteppingAction.cc.i
.PHONY : src/MuStoppedSteppingAction.i

# target to preprocess a source file
src/MuStoppedSteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedSteppingAction.cc.i
.PHONY : src/MuStoppedSteppingAction.cc.i

src/MuStoppedSteppingAction.s: src/MuStoppedSteppingAction.cc.s
.PHONY : src/MuStoppedSteppingAction.s

# target to generate assembly for a file
src/MuStoppedSteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MuStoppedSteppingAction.cc.s
.PHONY : src/MuStoppedSteppingAction.cc.s

src/MySensitiveDetector.o: src/MySensitiveDetector.cc.o
.PHONY : src/MySensitiveDetector.o

# target to build an object file
src/MySensitiveDetector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MySensitiveDetector.cc.o
.PHONY : src/MySensitiveDetector.cc.o

src/MySensitiveDetector.i: src/MySensitiveDetector.cc.i
.PHONY : src/MySensitiveDetector.i

# target to preprocess a source file
src/MySensitiveDetector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MySensitiveDetector.cc.i
.PHONY : src/MySensitiveDetector.cc.i

src/MySensitiveDetector.s: src/MySensitiveDetector.cc.s
.PHONY : src/MySensitiveDetector.s

# target to generate assembly for a file
src/MySensitiveDetector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exampleMuStopped.dir/build.make CMakeFiles/exampleMuStopped.dir/src/MySensitiveDetector.cc.s
.PHONY : src/MySensitiveDetector.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MuStopped"
	@echo "... exampleMuStopped"
	@echo "... exampleMuStopped.o"
	@echo "... exampleMuStopped.i"
	@echo "... exampleMuStopped.s"
	@echo "... src/MuStoppedActionInitialization.o"
	@echo "... src/MuStoppedActionInitialization.i"
	@echo "... src/MuStoppedActionInitialization.s"
	@echo "... src/MuStoppedDetectorConstruction.o"
	@echo "... src/MuStoppedDetectorConstruction.i"
	@echo "... src/MuStoppedDetectorConstruction.s"
	@echo "... src/MuStoppedEventAction.o"
	@echo "... src/MuStoppedEventAction.i"
	@echo "... src/MuStoppedEventAction.s"
	@echo "... src/MuStoppedPrimaryGeneratorAction.o"
	@echo "... src/MuStoppedPrimaryGeneratorAction.i"
	@echo "... src/MuStoppedPrimaryGeneratorAction.s"
	@echo "... src/MuStoppedRunAction.o"
	@echo "... src/MuStoppedRunAction.i"
	@echo "... src/MuStoppedRunAction.s"
	@echo "... src/MuStoppedSteppingAction.o"
	@echo "... src/MuStoppedSteppingAction.i"
	@echo "... src/MuStoppedSteppingAction.s"
	@echo "... src/MySensitiveDetector.o"
	@echo "... src/MySensitiveDetector.i"
	@echo "... src/MySensitiveDetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

